services:
  - type: web
    name: hono-api
    runtime: docker
    plan: free # Cambia a 'starter' o altro plan se necessario
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        sync: false # Da configurare nel dashboard Render
      - key: PORT
        value: 3001

